[package]
name = "rsharp"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
rsharp_macro = { path = "macro" }
paste = "1"
safer-ffi = "0.0.7"
