[package]
name = "rsharp"
version = "0.0.0"
edition = "2021"
# Prevent accidental `cargo publish`
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsharp_macro = { path = "macro" }
paste = "1"
safer-ffi = "0.0.7"
