language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --manifest-path=platform/Cargo.toml
  - cargo test --verbose --manifest-path=platform/Cargo.toml
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true