[package]
name = "platform"
version = "3.0.0"
edition = "2018"

[lib]
name = "teleportal_platform"
path = "src/lib.rs"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timer = "0.2.0"
chrono = "0.4.19"